# Generated by Django 2.2.28 on 2022-11-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_reg_user',
        ),
    ]
